sudo: false

language: python

cache:
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.4"
      env: TOXENV=py34
    - python: "3.5"
      env: TOXENV=py35

    - python: "2.7"
      env: TOXENV=pep8
    - python: "3.5"
      env: TOXENV=pep8py3

#branches:
#  only:
#    - master

install:
  - pip install tox

script:
  - tox
